language: node_js
node_js:
  - '0.10'
  - '0.11'
  - '0.12'
install:
  - npm install
before_install:
  - npm install -g gulp
  - npm install -g bower
  - bower install
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - gulp test-travis